### ISSUE TITLE
Error at the very end

### ISSUE THREAD

**Issue by CarlosRosuero** [img2tab/macos-guest-virtualbox#15]
Right at the last boot, when the Cygwin terminal asks to delete temporary files, the VM doesn't load macOS but rather this page:
![capture](https://user-images.githubusercontent.com/42518151/50772143-16940980-128d-11e9-8559-20d67d3e0146.PNG)

**Comment by hespy** [comment]
I can replicate the error as well in Cygwin at the same stage:

![image](https://user-images.githubusercontent.com/4170244/51029981-ecde2980-158f-11e9-88e5-6b00a6bc2288.png)

**Comment by hespy** [comment]
I manually progressed that bit in the end by.

Type FS1 hit enter.

Then changed dir as so:
cd "macOS Install Data"
cd "Locked Files"
cd "Boot Files"

Then type boot.efi and hit enter to continue.

**Comment by img2tab** [comment]
Updated "ostype" parameter to MacOS1013_64 per afboteros

**Comment by bsumners** [comment]
Hate to ask... but i am seeing the same issue. What is the resolution? For me it says FS1: is not a correct mapping. Almost as if it does not exist.
