### ISSUE TITLE
Very minor error at the end when cleaning up temporary files

### ISSUE THREAD

**Issue by keithzg** [img2tab/macos-guest-virtualbox#16]
Everything seems to have been fine, with one very minor exception: the script failed when trying to delete the temporary files at the end.
```
Press enter when the virtual machine shutdown is complete.
Waiting for VM "Mojave" to power on...
VM "Mojave" has been successfully started.

macOS Mojave 10.14.2 will now install and start up.

Delete temporary files? [y/n] y./macos-guest-virtualbox.sh: line 550: syntax error: unexpected end of file
```
The temporary files indeed appear to have not been cleaned up. No big deal, obviously, but figured it was worth mentioning.

I'm running *buntu 18.04.

**Comment by img2tab** [comment]
Forgot to close the if statement. Fixed.
