### ISSUE TITLE
Mojave virtual machine already exists. Exiting.

### ISSUE THREAD

**Issue by grumble9684** [img2tab/macos-guest-virtualbox#18]
I had to cancel the installation at one point and now I get this message every time. I deleted all the VM files in the script's home folder but it keeps saying the same thing even though no such VM is present in Virtualbox. What do I need to delete?

**Comment by keithzg** [comment]
You might need to also delete the folder in your VirtualBox machine folder? On Linux that's by default in `~/VirtualBox VMs` I believe, although if you open up Virtual Box and go File -> Preferences, and in the first section General you should see the Default Machine Folder. If you then go ahead and take a look in whatever folder is specified there, if you see a "Mojave" folder then delete that folder and try the script again, see if that solves it.

**Comment by img2tab** [comment]
You have to unregister the Mojave virtual machine for the script to continue. I'll add a line that unregisters it.
