### ISSUE TITLE
[not bug] shared folder

### ISSUE THREAD

**Issue by konrad-ch** [img2tab/macos-guest-virtualbox#20]
Hello! Is there a way to make shared folder between host system and macOS? Like with VirtualBox Guest Additions.

**Comment by img2tab** [comment]
There are a few ways to transfer files to a macOS guest, here's three:

- [SMB/FTP/SSH/rsync](https://support.apple.com/en-us/HT204445) over a [host-guest virtual network adapter](https://www.virtualbox.org/manual/ch06.html#network_hostonly) (probably slowest, but most robust)
- Create a VHD (Windows) or VMDK/raw (Linux) disk image and format it to EXFAT/FAT32/NTFS/..., mount it on the host, transfer files, then mount it on the macOS guest. (fastest, a little cumbersome)
- Create a VDI virtual disk image and format it to EXFAT/...,mount it on a guest OS that has Guest Additions (Fedora, Ubuntu, etc), transfer files, and later mount it on the macOS guest (even more cumbersome)
