### ISSUE TITLE
How to run with Cygwin?

### ISSUE THREAD

**Issue by MineMan9810** [img2tab/macos-guest-virtualbox#205]
I'm have no clue how to run the file with Cygwin. Sorry!

**Comment by myspaghetti** [comment]
1. Install [VirtualBox](https://www.virtualbox.org/wiki/Downloads)
2. Install [VirtualBox Extension Pack](https://www.virtualbox.org/wiki/Downloads)
3. Install [Cygwin](https://cygwin.com/install.html) with `bash` `coreutils` `gzip` `unzip` `wget` and `xxd` selected from the package list
4. Download [the script](https://raw.githubusercontent.com/myspaghetti/macos-guest-virtualbox/master/macos-guest-virtualbox.sh)
5. Run Cygwin/mintty, change the current directory to where the script is (`cd /cygdrive/c/Users/Public/Downloads` for example), and run the script (`bash ./macos-guest-virtualbox.sh`)
