### ISSUE TITLE
How to resize disk after installation?

### ISSUE THREAD

**Issue by rafalbednarczuk** [img2tab/macos-guest-virtualbox#21]

**Comment by img2tab** [comment]
From the host: `VBoxManage modifymedium "${virtual_disk_image_file}" --resize "${new_size_in_mb}"`
From the macOS guest: open Disk Utility and modify the disk partitions to your liking. macOS supports live disk partition resizes, creation, and deletion.

**Comment by unoqaz** [comment]
I ran `VBoxManage modifymedium Mojave.vdi --resize 40000`
and i get:
0%...
Progress state: VBOX_E_NOT_SUPPORTED
VBoxManage.exe: error: Failed to resize medium
VBoxManage.exe: error: Resizing to new size 41943040000 is not yet supported for medium 'C:\cygwin64\home\username\Mojave.vdi'
VBoxManage.exe: error: Details: code VBOX_E_NOT_SUPPORTED (0x80bb0009), component MediumWrap, interface IMedium
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleModifyMedium(struct HandlerArg *)" at line 768 of file VBoxManageDisk.cpp
