### ISSUE TITLE
Works on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by bronson** [img2tab/macos-guest-virtualbox#22]
A Debian guest running in WSL worked great. This script is really impressive.

To prepare, I only had to make VBoxManage.exe available as VBoxManage. I did it like this:

    sudo apt-get dmg2img unzip wget
    mkdir -p ~/bin
    ln -s /mnt/c/Program\ Files/Oracle/VirtualBox/VBoxManage.exe ~/bin/VBoxManage
    export PATH=~/bin:$PATH

If you think it's worth it, I could send a PR that prepares a WSL path similar to how it currently prepares a Cygwin path and calls VBoxManage.exe if VBoxManage is missing.

**Comment by bronson** [comment]
Oh, I should mention that sometimes I had to hit <space><enter> when it was asking "Press enter when something is ready". It ignored plain <enter>. Probably some WSL incompatibility.

**Comment by img2tab** [comment]
I have no experience with WSL but I believe Cygwin is more portable and WSL is only available for Windows 10, so I believe I'll stick with Cygwin unless there are other advantages to WSL.

**Comment by img2tab** [comment]
Oh you're suggesting installing the dependencies with WSL... that would require detecting whether WSL is available or not. Better not add complexity unless there's a compelling reason.

**Comment by jonathanweinberg** [comment]
I don't think @bronson is implying to get rid of the Cygwin method, but eventually, WSL will be very mainstream. Just an option to allow easier adoption/use.

**Comment by img2tab** [comment]
I'd gladly accept a pull request with an if statement that identifies running under WSL and adds VBoxManage to PATH, but I would like to keep everything under one working directory (no creating symlinks in ~/bin) and avoid elevating privileges (ask the user to manually install the packages).

**Comment by bronson** [comment]
Yes, I agree with all those points. If I can find some time to try to get iMessage going again, I'll put together a PR.  (won't be the next few weeks tho!)

Closing since this is now a wishlist item.
