### ISSUE TITLE
"Command Not Found" screen corruption during install

### ISSUE THREAD

**Issue by bronson** [img2tab/macos-guest-virtualbox#23]
Not quite sure what happened here but it was only cosmetic -- the script kept running.

```
When the installer finishes preparing, the virtual machine will reboot
into the base system, not the installer.

After the reboot, press enter when the Language window ./macos-guest-virtualbox.sh: line 491: or Utilities window is ready.\033[0m: command not found


Press enter when the macOS Utilities window is ready.
```

Although seeing "command not found" was a little scary, I could proceed as if nothing strange had happened.

**Comment by matheusware** [comment]
On line 481 I believe

`printf ${whiteonblack}'
After the reboot, press enter when the Language window '
'or Utilities window is ready.'${defaultcolor}`

should be 

`printf ${whiteonblack}'
After the reboot, press enter when the Language window 
or Utilities window is ready.'${defaultcolor}`

without the stray quotes between the words 'window or'

but it doesn't appear to affect the functionality of the script

**Comment by img2tab** [comment]
Fixed.
