### ISSUE TITLE
The MacOS Download link has gone stale

### ISSUE THREAD

**Issue by juancgarcia** [img2tab/macos-guest-virtualbox#26]
When coming on this step, wget-ing the files results in 404 or other errors downloaded instead of the needed files.

![image](https://user-images.githubusercontent.com/1028635/51769561-6e19de00-20b1-11e9-99d3-9d2c9b522e21.png)

https://github.com/img2tab/macos-guest-virtualbox/blob/7c4f8944302707f603d2a9d76e2b5d187736340b/macos-guest-virtualbox.sh#L418-L419

**Comment by NickAmes** [comment]
Also having this issue.

**Comment by user747** [comment]
Had same issue. I think its server side. Using a VPN allows me to download it.

**Comment by img2tab** [comment]
Updated URL.
