### ISSUE TITLE
Can't determine BASH_VERSION. Exiting.

### ISSUE THREAD

**Issue by alizardx** [img2tab/macos-guest-virtualbox#30]
i'm running ubuntu 16.04 
tried running script, it terminated. \e[48;2;0;0;9m\e[38;2;255;255;255mPress enter to continue, CTRL-C to exit.macos-guest-virtualbox.sh: 46: read: arg count
Can't determine BASH_VERSION. Exiting.

checked bash version;
bash is already installed at the latest version (4.3-14ubuntu1.2), so it will not be upgraded.

**Comment by yannicklescure** [comment]
Same error on Ubuntu 18.04

**Comment by alizardx** [comment]
tried current version, same error

**Comment by img2tab** [comment]
Attempted to reproduce on Ubuntu 16.04 and 18.04. The script runs successfully. The error is generated only when executing the script with sh instead of bash. Please execute the script with `/bin/bash macos-guest-virtualbox.sh`

**Comment by yannicklescure** [comment]
I confirm it works. "/bin/bash macos-guest-virtualbox.sh" shoud be indicated in the README.md
