### ISSUE TITLE
Stuck in UEFI shell.

### ISSUE THREAD

**Issue by distinguished-git** [img2tab/macos-guest-virtualbox#32]
Host: Fedora 29 x64

Stuck after:
```
Detaching initial base system and starting virtual machine.
The VM will boot from the new base system on the installer virtual disk.
Waiting for VM "Macintosh HD" to power on...
VM "Macintosh HD" has been successfully started.

Press enter when the Language window is ready.
```

I've run into issue #15 , where on (possiblly the final?) boot, it sends me to the UEFI shell. FS0 and FS1 are empty. FS2 has a directory with no name, somehow. 

Sorry, I wasn't sure if anyone would see my comment in a closed issue so I opened a new one. Unsure of the protocol there.

I tried the solutions in issue #15 , but as I said the .efi file is inaccessible to me. If it exists, it is probably in a directory with no name.

Also, the OS is already set as High Sierra 64-bit in settings, even though we are installing Mojave.

The only changes I've made to the installer script were these variables: vmname (Macintosh HD), storagesize (48000), memorysize (2048), gpuvram (34), serialnumber, devicename, boardid (last 3 copy/pasted from About This Mac).

Help, please?

![screenshot_20190201_090626](https://user-images.githubusercontent.com/34387989/52127691-d102fc00-2600-11e9-9073-9a82e5fd63ca.png)

![screenshot_20190201_091052](https://user-images.githubusercontent.com/34387989/52127824-48389000-2601-11e9-8048-bf04fb6b3e46.png)

**Comment by distinguished-git** [comment]
Downgrading from Virtualbox-6.0 to 5.2 seems to have helped. I also used these drivers: https://thetechbloggerguy.blogspot.com/2018/12/apfs-efi-iso.html

**Comment by img2tab** [comment]
Using VirtualBox 6.0 and AppleSupport-v2.0.4-RELEASE.zip, could not reproduce.

**Comment by meadows19** [comment]
Same error here, using VirtualBox 6.0.8

Stuck on the UEFI shell.

The installer script is on "Press enter when the language window is ready"

**Comment by img2tab** [comment]
@meadows19 please attach the log file `VBox.log` to your comment. You can find this file [as described here](https://blogs.oracle.com/scoter/virtualbox-log-files-v2).
