### ISSUE TITLE
Automatically parse Apple catalog

### ISSUE THREAD

**Issue by img2tab** [img2tab/macos-guest-virtualbox#33]
Requested enhancements:

- Windows Subsystem on Linux support (requires minimal adjustments)
- Resume at selected step
- Select virtual disk size

**Comment by img2tab** [comment]
Instead of letting users specify the virtual disk size, I changed the disk image type to "standard" (instead of "fixed") so users can resize it after installation.

**Comment by abonander** [comment]
It would still be nice not to have to manually resize it later.

**Comment by img2tab** [comment]
Another nifty enhancement would be parsing `http://swscan.apple.com/content/catalogs/others/index-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog` for the download URLs so the script doesn't have to be manually updated whenever Apple updates Mojave.

**Comment by img2tab** [comment]
WSL apparently works now. That leaves resuming and Apple catalog parsing.

**Comment by img2tab** [comment]
Resuming kinda-sorta works. WSL is still untested but _should_ work. Parsing the Apple catalog automatically would be nice.

**Comment by img2tab** [comment]
Implemented in version 0.51
