### ISSUE TITLE
How long should it take before I see the Language window?

### ISSUE THREAD

**Issue by ilovecats516** [img2tab/macos-guest-virtualbox#34]
It has been taking a long time and I haven't seen the Language window yet. How long should it take?

Thanks.

**Comment by ilovecats516** [comment]
Update: I'm stuck at the Apple logo and loading bar. It's been like an hour.
![capture](https://user-images.githubusercontent.com/30846409/52457427-84428800-2b0e-11e9-903b-26407babf70b.PNG)

**Comment by ilovecats516** [comment]
Just found out I am using the wrong version of Virtualbox.

**Comment by myspaghetti** [comment]
Added VirtualBox version check in 0.65.0 or slightly earlier, and later reduced version requirement to 5.2.2 in script version  0.71.3
