### ISSUE TITLE
Trying to start the VM from VM Manager fails.

### ISSUE THREAD

**Issue by Aashitisaashit** [img2tab/macos-guest-virtualbox#35]
It installs and works. I then use the .vdi file to create and run a Mac VM from the virtual box VM manager.

After this it doesn't boot the OS. Gets stuck in a loop as shown in the screenshot below ,after which it  restarts. 

Specs : Manjaro , Linux Kernel 4.14 , VB VM version 6
![screenshot from 2019-02-08 20-24-27](https://user-images.githubusercontent.com/42736461/52478257-c38cd980-2bdf-11e9-86e1-77802858feac.png)

**Comment by img2tab** [comment]
The vdi is not sufficient, you need to configure the VM correctly. See all the lines 207 through 225 inclusive:

`VBoxManage modifyvm "${vmname}" --cpus "${cpucount}" --memory "${memorysize}" \
 --vram "${gpuvram}" --pae on --boot1 dvd --boot2 disk --boot3 none \
 --boot4 none --firmware efi --rtcuseutc on --usbxhci on --chipset ich9 \
 --mouse usb --keyboard usb --audio none --ostype "MacOS1013_64"
VBoxManage setextradata "${vmname}" \
 "VBoxInternal/Devices/efi/0/Config/DmiSystemProduct" "${devicename}"
VBoxManage setextradata "${vmname}" \
 "VBoxInternal/Devices/efi/0/Config/DmiSystemVersion" "1.0"
VBoxManage setextradata "${vmname}" \
 "VBoxInternal/Devices/efi/0/Config/DmiBoardProduct" "${boardid}"
VBoxManage setextradata "${vmname}" \
 "VBoxInternal/Devices/smc/0/Config/DeviceKey" \
 "ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"
VBoxManage setextradata "${vmname}" \
 "VBoxInternal/Devices/smc/0/Config/GetKeyFromRealSMC" 1
VBoxManage setextradata "${vmname}" \
 "VBoxInternal2/EfiGraphicsResolution" "${resolution}"
VBoxManage setextradata "${vmname}" \
"VBoxInternal/Devices/efi/0/Config/DmiSystemSerial" "${serialnumber}"`

**Comment by Aashitisaashit** [comment]
@img2tab Thanks. Thought I could set the settings from within the VB Manager. Anyways, Now it does boot up but the keyboard and mouse don't respond. I get the blinking caret on the lockscreen so I know it isn't stuck. But no response from any input devices, USB or otherwise

**Comment by Aashitisaashit** [comment]
One thing that I'll add is that I am running a Sierra VM and that works well with input devices

**Comment by Aashitisaashit** [comment]
Thanks. I thought I could set it up from within the manager. I am facing another issue with regards to the VRAM being used by the VM. After allotting it 256mb of VRAM, It only takes up 7mb. I have been through a lot of websites pertaining to hackintosh but havent been able to get it to work. Have you any advice to resolve this from your past experiences ? I am working with Intel Core i7-8750H processor and nvidia gtx 1080.
