### ISSUE TITLE
Problems with spaces in virtual machine name

### ISSUE THREAD

**Issue by dslc** [img2tab/macos-guest-virtualbox#40]
At the

> Loading base system onto installer virtual disk ...

stage, the command

```bash
asr restore ...
```

fails if the virtual machine name includes spaces - [here](https://github.com/img2tab/macos-guest-virtualbox/blob/0a219040d6548fa7afff3be27848fc532ff3a46a/macos-guest-virtualbox.sh#L453).

I am conscious it may not be a good idea to include spaces in a machine name anyway, but just thought it would be worth highlighting this.

**Comment by img2tab** [comment]
Fixed with version 0.39! That was the _one_ place I forgot to put the directory name in quotes!

**Comment by dslc** [comment]
Thanks for the response - and the excellent work on this project.
