### ISSUE TITLE
keyboardputscancode fail on WSL

### ISSUE THREAD

**Issue by rabievdm** [img2tab/macos-guest-virtualbox#42]
I have managed to get some progress with setting the paths under WSL.
The disk images gets created up until the Language screen, now however the keyboard commands are not being entered.

I'm getting:
VBoxManage.exe: error: Missing argument to 'keyboardputscancode'. Expected IBM PC AT set 2 keyboard scancode(s) as hex byte(s).

However it does work if I call the same command and scancodes from the comandline. So I have to assume it's not processing the lookups correctly. Will dig a little more, but any help would be appreciated.

**Comment by karottenbaum** [comment]
I'm experiencing this with Zsh and bash on Ubuntu. With set -x, it seems that keyboardputscancode is being called with scancodes of `' '`.

**Comment by img2tab** [comment]
@rabievdm @karottenbaum please make sure you are using Bash version 4.0 or higher*. zsh is unsupported. Make sure bash is called when subshells are called from the script with "$(...)"

*this is required for dictionary variables, without which the scancodes dictionary would be very tedious to use in Bash

**Comment by rabievdm** [comment]
I'm on bash 4.4 (which is my default shell in WSL running Ubuntu 18.04.2 LTS )
I open a bash prompt and then I run the script in the shell.
Google seems to talk about local/global variables, but I'm not 100% sure what I need to do with the $(...)

**Comment by Dev0110** [comment]
I got the same issue even using Cygwin.

**Comment by img2tab** [comment]
Seems like Bash doesn't export the dictionary out of the local state of the function, which is weird because it happily exports other variables out of functions without any regard to local/global states. Moved it out of the function. Should be fixed now with version 0.48.

**Comment by Dev0110** [comment]
Works with the new version.
Thanks !

**Comment by img2tab** [comment]
Fixed
