### ISSUE TITLE
Mojave installer fails during "preparation"

### ISSUE THREAD

**Issue by itsrainingcode** [img2tab/macos-guest-virtualbox#49]
The Mojave installer fails during the preparation stage at roughly 73%. I retried the script from the beginning, deleting all temp files, and re-downloading as suggested in #24, thinking it might have been a corrupted download or something. It failed again at nearly the same %.

There were no visible errors during any of the previous steps, other than VirtualBox warning about "critical disk space" as noted by the script.

However, increasing the size of the installer virtual disk to the [recommended](https://support.apple.com/en-us/HT201372) 12GB solved the problem. The third try was successful. Maybe some recent updates have pushed the installer size beyond the original 8GB allocated by the script?

**Comment by img2tab** [comment]
Thank you, will fix.

**Comment by img2tab** [comment]
Fixed in version 0.59
