### ISSUE TITLE
Error during Loading base system onto installer virtual disk

### ISSUE THREAD

**Issue by ComaToph** [img2tab/macos-guest-virtualbox#5]
I have to admit I'm new to this, but this script is exactly what I'm looking for - installing MacOS on the VirtualBox VM.  I've resolved a couple of issues, like installing the VirtualBox Expansion Pack to enable USB 2.0/3.0 support and prefixing 'string:' to the extradata DmiSystemSerial value mentioned in the other issue.

However now when I get to the 'Loading base system onto installer virtual disk' step, I get an error in the bash terminal window that it can't find the restore command (see attached screenshot).  Am I missing an environment variable maybe?

![image](https://user-images.githubusercontent.com/45299048/48961145-edffbc80-ef37-11e8-9d9a-a5f51b4edd67.png)

**Comment by img2tab** [comment]
There is a bug where any stray keyboard input breaks the script. The script should [clear stdin before sending keys to the virtual machine](https://superuser.com/questions/276531/clear-stdin-before-reading), but the solution is even hackier than the current state of the script so I'm reluctant to use it.

**Comment by img2tab** [comment]
Used hacky solution.
