### ISSUE TITLE
Check for VirtualBox Extension Pack

### ISSUE THREAD

**Issue by logoff** [img2tab/macos-guest-virtualbox#50]
Hello.

I'm trying to run your script with my Ubuntu 18.04 and VirtualBox 6.0 and I get a lot of random errors like:

`VBoxManage: error: Failed to send a scancode`

Then the commands to be executed in terminal got corrupted, usually I see the last letter of current command sent repeated indefinitely. I tried to introduce all of them manually, but there is a lot of them...

I don't why I get these errors. Any clue?

**Comment by logoff** [comment]
I found that VirtualBox Extension Pack was not correctly installed. After reinstalling it, it seems that everything worked better. There is no issue at all ;)

**Comment by img2tab** [comment]
The script should probably check whether VirtualBox Extension Pack sends scancodes correctly. I'll implement this sooner or later.

**Comment by img2tab** [comment]
Fixed in version 0.60
