### ISSUE TITLE
The disk doesn't have enough free space to download AppleSupport

### ISSUE THREAD

**Issue by schdck** [img2tab/macos-guest-virtualbox#52]
In the step where I should manually download the AppleSupport-v2.0.4-RELEASE.zip, I receive the folowing error on Safari:

> **Safari could not download the file "AppleSupport-v2.0.4-RELEASE.zip" because the disk does not have enough free space.**
> Try deleting documents or downloading to another disk.

However, if I open the Disk Utility, it appears that "Mojave" has 43.9GB free and "macOS Base System" 4.82GB.

---

**Environment:**

I'm running WSL (Ubuntu) on Windows 10 1809 Home Single Language.

Here's my settings

    vmname="Mojave"
    storagesize=48000
    cpucount=4
    memorysize=8192
    gpuvram=128
    resolution="1980x1080"
    serialnumber="NOTAVALIDSN0"
    devicename="MacBookPro11,3"
    boardid="Mac-2BD1B31983FE1663"

**Comment by schdck** [comment]
My bad, didn't notice that I should use 'Download Linked File As...' 🤦‍♂️

**Comment by img2tab** [comment]
I'll make the instructions more clearly visible on the next version.

**Comment by flamecopper** [comment]
Yes, initially face this issue as well, Choose Mojave location and it worked.
Anyway trying to setup xcode.
