### ISSUE TITLE
Linux Host, Mouse jumping around and stuck bounds

### ISSUE THREAD

**Issue by psywhale** [img2tab/macos-guest-virtualbox#53]
Linux host: Ubuntu 18.04

Virtualbox: Version 6.0.6 r130049 (Qt5.9.5)

Mouse will jump around and click things randomly. Also seems to be stuck in a box sometimes.

[Video Recording](https://youtu.be/BxgcdzvacRQ)

**Comment by img2tab** [comment]
This appears to be a bug with VirtualBox, which is beyond the scope of this project. If this is a result of a misconfiguration from the script, it probably has to do with the USB 3.0 (xHCI USB) being disabled. Please make sure that the VirtualBox Extension Pack is installed and:

* The USB controller is enabled and set to USB 3.0 (xHCI)
* The chipset is set to ICH9
* The pointing device is set to USB Mouse and the keyboard is set to USB Keyboard

This is all set by default by the script (`--usbxhci on --chipset ich9 --mouse usb --keyboard usb`)

**Comment by psywhale** [comment]
Found a workaround... 

On the same host, I have Sierra working with no problems. Looking at its config, I noticed the mouse was set to "USB Tablet".  Changed Mojave vm to USB Tablet and so far no problems..

**Comment by alexandre-janniaux** [comment]
Same issue, same fix for me.

**Comment by img2tab** [comment]
@alexandre-janniaux @psywhale is there a way to detect that your "mouse" is "USB Tablet" and not "USB"?

**Comment by lesreaper** [comment]
I have the same problem, and all of my settings are correct for USB.

**Comment by img2tab** [comment]
@lesreaper does changing the Mouse settings to "USB Tablet" fix the problem? And if so, what is your pointing device?

**Comment by lesreaper** [comment]
Wow, that was fast, I was just going to delete the comment. 

Yes, switching it to USB tablet worked. Thanks!

**Comment by alexandre-janniaux** [comment]
@img2tab my mouse is an usb 5-button mouse, so I don't really know. It might be fixed with some UX, having your script asking if the mouse is bouncing and getting stuck when moving it. It should probably be before the safari step though, it was a bit hard to reach.

**Comment by img2tab** [comment]
Instead of asking the user I'll just set the `mouse` option to `usbtablet` by default. The only negative effect is the pen pressure settings pane in System Preferences.
