### ISSUE TITLE
Download InstallESDDmg.pkg (6GB file) to host for easier resuming

### ISSUE THREAD

**Issue by ciampix** [img2tab/macos-guest-virtualbox#55]
This is a wish for an improvement, not really a bug.
The script should avoid downloading again and again the same MacOSX image if it find it already downloaded from a previously run of the same script. I ask this because, especially at start, it is easy to make mistakes and run it more than once, and downloading the already downloaded the same (big) image file could be a nice improvement...
that's all

**Comment by img2tab** [comment]
This is relatively easy to implement with VirtualBox 6 thanks to the [VISO file format](https://docs.oracle.com/cd/E97728_01/F12469/html/viso.html). For some reason though, `RTIsoMaker` doesn't ship with the Windows version of VirtualBox even though it can create VISO files through the GUI. The VISO file format is very simple but I don't want to reinvent the wheel here.

The design concept for this enhancement is: download all the files to the host (from Apple - `BaseSystem.chunklist` `InstallInfo.plist` `AppleDiagnostics.dmg` `AppleDiagnostics.chunklist` `BaseSystem.dmg` `InstallESDDmg.pkg`; from github - `AppleSupport-v2.0.4-RELEASE.zip`) and point to them in a VISO file that's just a plaintext file. This will allow everything to be downloaded ahead of the creation of the VM and reduce the number of reboots and the amount of required user interaction.

This can all be done right now by making `RTIsoMaker` a requirement. Doing this without `RTIsoMaker` is slightly more roundabout and probably not worth switching over from the current design.

**Comment by ciampix** [comment]
Yes but I thought about a much simpler solution: just two lines of check in the script... something like ...
 if [ file already present] ; jump the download part ...
they should suffice. I can try do it myself and post a PR...

**Comment by img2tab** [comment]
You mean inside the virtual machine? `curl -C -` already does that.

**Comment by ciampix** [comment]
Ok found ... avoid this (or ask before doing it):

   if [ -s BaseSystem.vdi ]; then
        rm "BaseSystem.dmg" "BaseSystem.img" 2>/dev/null
    fi

because if you want to re-run the script you have to re-download the BaseSystem.dmg that is huge...
I mean: it would be nice to be able to re-run the script without re-download huge files all the time...

**Comment by img2tab** [comment]
`BaseSystem.dmg` and `BaseSystem.img` are deleted to save storage space. If you already have `BaseSystem.vdi` then the script does not re-download `BaseSystem.dmg`.

**Comment by img2tab** [comment]
Heads up: with macOS Catalina recovery environment not shipping with a working copy of `curl`, it's likely I'll eventually implement the `VISO` solution and the script will require VirtualBox ≥ 6

**Comment by img2tab** [comment]
Implemented in [version 0.65.0](https://github.com/img2tab/macos-guest-virtualbox/releases/tag/v0.65.0)
