### ISSUE TITLE
better display driver

### ISSUE THREAD

**Issue by legale** [img2tab/macos-guest-virtualbox#58]
https://github.com/ivanagui2/VMQemuVGA/releases

What do you think about it?

**Comment by img2tab** [comment]
You can change the display resolution with the command `VBoxManage setextradata "${vmname}" "VBoxInternal2/EfiGraphicsResolution" "${resolution}"`

That repository, whatever you intend to do with it, seems to have a license issue. Code licensed under GPLv2 cannot be relicensed under the MIT license.
