### ISSUE TITLE
Virtual Machine not starting

### ISSUE THREAD

**Issue by thoernle** [img2tab/macos-guest-virtualbox#60]
I used the script and after that I tried to start the VM with:
`vboxmanage startvm macOS_Mojave_GE`
Got the following result:

> vboxmanage startvm macOS_Mojave_GE
Waiting for VM "macOS_Mojave_GE" to power on...
VBoxManage: error: The virtual machine 'macOS_Mojave_GE' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

**Comment by img2tab** [comment]
@thoernle please attach the `macOS_Mojave_GE` log file `VBox.log` to your comment. You can find this file [as described here](https://blogs.oracle.com/scoter/virtualbox-log-files-v2).

**Comment by img2tab** [comment]
Closing until further details are provided
