### ISSUE TITLE
Serial number

### ISSUE THREAD

**Issue by mikekenyon99** [img2tab/macos-guest-virtualbox#62]
When you say a genuine serial number can I use the one from my existing MacBook?  Or will that lock it out from Apple?  I have looked on the net for ones and they tell me to use Clover Configurator - but how do I do that on this image?

Thanks

**Comment by img2tab** [comment]
Yes, using the serial number, board ID, and product/device name/identifier from an existing MacBook works, and even slightly changing the serial works. You can either configure this in the script before installation, or after installation with the following commands:
```
VBoxManage setextradata "${vmname}" "VBoxInternal/Devices/efi/0/Config/DmiSystemProduct" "${devicename}"
VBoxManage setextradata "${vmname}" "VBoxInternal/Devices/efi/0/Config/DmiBoardProduct" "${boardid}"
VBoxManage setextradata "${vmname}" "VBoxInternal/Devices/efi/0/Config/DmiSystemSerial" "${serialnumber}"
```

You can find various examples of product/board pairs (sometimes with serial) on github.

**Comment by o6uoq** [comment]
I've changed my installation script to include all of the settings required from a working Mac (Catalina, but was previously Mojave) and when used on the Mojave install via your script, it says I cannot register for Apple ID.

**Comment by myspaghetti** [comment]
Registering a new Apple ID requires additional parameters, and I don't know what they are. If you know which parameters are missing please post their NVRAM names/addresses here. It's also possible the OS is querying the SMC, which can be virtualized with OpenCore. For newer devices, it's possible the OS is querying the T2 security chip, which probably cannot be virtualized.

**Comment by o6uoq** [comment]
I ran the script to update my variables, rebooted macOS, and have connected my iCloud account with no worries 👍
