### ISSUE TITLE
win11 执行脚本报错 Check that software such as Hyper-V, Windows Sandbox, WSL2, memory integrity protection, and other Windows features that lock virtualization are turned off.

### ISSUE THREAD

**Issue by PaiGack** [img2tab/macos-guest-virtualbox#663]
实际上在本机运行其他虚拟机操作系统并无问题
![image](https://github.com/myspaghetti/macos-virtualbox/assets/42209827/3fb67e3e-09a8-4f87-9961-d3d9b1c3ce62)

**Comment by myspaghetti** [comment]
Please search for existing issues about Hyper-V. Some people report that executing the following command and rebooting twice disables Hyper-V:
```
bcdedit /set hypervisorlaunchtype off 
```
