### ISSUE TITLE
MacOS boots into recovery mode instead of MacOS Desktop.

### ISSUE THREAD

**Issue by ghost** [img2tab/macos-guest-virtualbox#664]
After downloading all the necessary dependencies, the bash install runs perfectly and is successful for Virtualbox. 
However, the MacOS only boots into recovery mode. 
Currently running a 6.3.0-kali1-amd64 system.
I decided to delete the VM with the option, "All Files." 
How may I ensure that I deleted everything that the bash script installed?
I will install macos-virtualbox once this issue is fixed. Thank you.

**Comment by myspaghetti** [comment]
The VM boot is a four-part process. The VM first boots and checks VirtualBox is using hardware acceleration, then it boots into the recovery volume and creates the bootable installer, then it boots into the bootable installer and creates the installation volume, then it boots into the installation volume and installs macOS.

The script downloads files only to its working directory, so you can delete all the files from the script's working directory. VirtualBox creates files under its defined VM directory and creates/edits a configuration file in the defined VB configuration directory. Nothing else is changed by the script, not including packages manually installed by the user.
