### ISSUE TITLE
Installation script is pending on Press enter when the Language window is ready.

### ISSUE THREAD

**Issue by Tim-Cao** [img2tab/macos-guest-virtualbox#665]
Could you help me investigate this issue?
![Installation](https://github.com/myspaghetti/macos-virtualbox/assets/52661397/9dd098a0-db96-4149-b009-c5e95aacdc1c)
I installed it on Oracle VM VirtualBox 7.0
My OS is ubuntu 22.04

**Comment by Tim-Cao** [comment]
The Intel Core i7-3960X of cpu profile works for me.

**Comment by Chi-Iroh** [comment]
Thanks, it also works for me.
