### ISSUE TITLE
stage populate_bootable_installer_virtual_disk -> checksum faild

### ISSUE THREAD

**Issue by artem-totality** [img2tab/macos-guest-virtualbox#667]
Stuck on stage populate_bootable_installer_virtual_disk. What can I do? 

![Снимок экрана_2023-09-17_07-54-18](https://github.com/myspaghetti/macos-virtualbox/assets/67862776/2e9c069e-2405-4a65-b50f-4457af862b9c)

**Comment by myspaghetti** [comment]
This can occur [when the disk is full, when the CPU is not supported, or when the installation files on the host are corrupt.](https://github.com/myspaghetti/macos-virtualbox/issues/439)

You can check the MD5 sums on the host:
```
363aafb01775d361c3c95a3b4540e44f  Catalina_BaseSystem.chunklist
e8b106cc85ac71f2eb2fe2e4eb62357c  Catalina_BaseSystem.dmg
c39544720166ae77fd4795340c166289  Catalina_InstallESDDmg.pkg
37f6018df93ece4a57a7ddffad1edf2b  Catalina_InstallESD.part00
bd88dccae42d172c5f853e7c90d392bf  Catalina_InstallESD.part01
7797b9b9155e6fe36f1c913a1332cb1e  Catalina_InstallESD.part02
8fc9fff5b3da0caa1d58dba49ba782d9  Catalina_InstallESD.part03
183bee8a87c8ed75188cc2904e55d9d6  Catalina_InstallESD.part04
d97a3411ff914786a28cfb09de964a38  Catalina_InstallESD.part05
72e32b668be86afcda65a07818f73c64  Catalina_InstallESD.part06
fbb62a5a148c3ffb567f9d99ff1cf11d  Catalina_InstallESD.part07
81d00dfb92442baad965fdfba77e4d92  Catalina_InstallInfo.plist
422384c9eb4d599f2dd4e8f0b62c31d9  Catalina_AppleDiagnostics.chunklist
b03b3beaa4db7dbee013f45d94096842  Catalina_AppleDiagnostics.dmg
```

**Comment by artem-totality** [comment]
@myspaghetti 

All md5 sums is the same:

![md5sums](https://github.com/myspaghetti/macos-virtualbox/assets/67862776/9c5c9d8b-d579-4246-8faa-3b01a0e01401)

my CPU is

`CPU: Intel i5-2410M (4) @ 2.300GHz `

free space on /home is 80GB 

`/dev/sda2        160159924     65744484 86207056           44% /home`
