### ISSUE TITLE
Script not completing

### ISSUE THREAD

**Issue by Timmaaahh** [img2tab/macos-guest-virtualbox#668]
Dear Dev's,

I try to run the script, but it fails:

![Screenshot 2023-10-04 045345](https://github.com/myspaghetti/macos-virtualbox/assets/64709989/95c3bbe6-e562-409b-9ceb-2a96bc0f3e54)

VBox version is 7, and the path  to VBoxManage.exe is set. 
I'm running Windows 11,  and i've got all required dependencies installed.

Help is much appreciated.

-Tim

**Comment by myspaghetti** [comment]
Duplicate
https://github.com/myspaghetti/macos-virtualbox/issues/525
