### ISSUE TITLE
Bash history contains script commands

### ISSUE THREAD

**Issue by vincss** [img2tab/macos-guest-virtualbox#671]
Hi !
Thank you for your good work, it works well.

Since I used the script, my history is always full with commands from this script, do you have any ideas how to get rid of it ?

`$ history
    1  This script installs only open-source software and unmodified Apple binaries,
    2  and requires about ${highlight_color}50GB${default_color} of available storage, of which 25GB are for temporary
    3  installation files that may be deleted when the script is finished.
    4  The script interacts with the virtual machine twice, ${highlight_color}please do not interact${default_color}
    5  ${highlight_color}with the virtual machine manually${default_color} before the script is finished.
    6  Documentation about optional configuration, ${highlight_color}iCloud and iMessage connectivity${default_color},
    7  resuming the script by stages, and other topics can be viewed with the
    8  following command:
    9  "; would_you_like_to_know_less; echo -ne "\n${highlight_color}Press enter to review the script configuration${default_color}"; clear_input_buffer_then_read;  function pad_to_33_chars() {     local padded="${1}                                 ";     echo "${padded:0:33}${2}"; };
   10  echo -e "\nvm_name=\"${vm_name}\""; pad_to_33_chars "macOS_release_name=\"${macOS_release_name}\"" "# install \"HighSierra\" \"Mojave\" \"Catalina\""; pad_to_33_chars "storage_size=${storage_size}"                 "# VM disk image size in MB, minimum 22000"; pad_to_33_chars "storage_format=\"${storage_format}\""         "# VM disk image file format, \"vdi\" or \"vmdk\""; pad_to_33_chars "cpu_profile=\"${cpu_profile}\""               "# VM CPU profile, see \"CPU profiles\" in docs"; pad_to_33_chars "cpu_count=${cpu_count}"                       "# VM CPU cores, minimum 2"; pad_to_33_chars "memory_size=${memory_size}"                   "# VM RAM in MB, minimum 2048"; pad_to_33_chars "gpu_vram=${gpu_vram}"                         "# VM video RAM in MB, minimum 34, maximum 128"; pad_to_33_chars "resolution=\"${resolution}\""                 "# VM display resolution"; echo -ne "\nThese values may be customized as described in the documentation.\n
   11  ${highlight_color}Press enter to continue, CTRL-C to exit${default_color}"; clear_input_buffer_then_read; }`

Have a nice day.

**Comment by myspaghetti** [comment]
Please see issue #642 for possible workarounds.
