### ISSUE TITLE
Blocked on "Otherwise, please wait."

### ISSUE THREAD

**Issue by Mijsoot** [img2tab/macos-guest-virtualbox#672]
Hello and thank you for your work! 
For information I am on Windows 11 and a fresh installation of Cygwin.
I had to install a lot of dependencies obviously and I had to disable the memory integrity check to succeed in installing.
Here's what I also had to change in the script :

```
wgetargs="--quiet --continue --show-progress --timeout=60 --secure-protocol=PFS"  # pretty
wgetargs="--no-check-certificate --quiet --continue --show-progress --timeout=60 --secure-protocol=PFS"  # pretty

wgetargs="--continue"  # ugly
wgetargs="--no-check-certificate --continue"  # ugly

cmd_path_VBoxManage='C:\Program Files\Oracle\VirtualBox\VBoxManage.exe'
cmd_path_VBoxManage='D:\VirtualBox\VBoxManage.exe'
```

Once the installation is complete, which seems to have gone well, the screen remains stuck on "Otherwise, please wait." 
Should I wait any longer? It's been 3 hours! What can I do?

![macos-virtualbox_30_11_23_1](https://github.com/myspaghetti/macos-virtualbox/assets/22812111/76c11ed0-8fa3-4af9-b359-bbed5fff6c59)
![macos-virtualbox_30_11_23_2](https://github.com/myspaghetti/macos-virtualbox/assets/22812111/2055a88f-3649-4d08-8dea-6f3094d93dc9)
![macos-virtualbox_30_11_23_3](https://github.com/myspaghetti/macos-virtualbox/assets/22812111/640f339b-aa35-4c74-90c7-8d5ab62b5a50)
![macos-virtualbox_30_11_23_4](https://github.com/myspaghetti/macos-virtualbox/assets/22812111/268ce63a-cec6-44bb-812b-8d3b4c3fb076)

**Comment by myspaghetti** [comment]
Hi, thanks for the detailed bug report!

The "EXITBS" message indicates a CPU incompatibility. Please see the CPU compatibility section in the readme on github or the documentation.

**Comment by Mijsoot** [comment]
Oh! Thanks and sorry I hadn't read the CPU incompatibility part ....

My processor is an AMD Ryzen 5 5600G with Radeon Graphics, 3901 MHz, 6 core(s), 12 logic processor(s), do you think I can manage to modify VirtualBox so that it works? I don't quite understand the principle of "Teleporting Settings".
