### ISSUE TITLE
NEM/Hyper-V

### ISSUE THREAD

**Issue by loopy321** [img2tab/macos-guest-virtualbox#673]
FYI, I was able to get this installed by doing the following changes to the script.  
It was exiting at[ line 476](https://github.com/myspaghetti/macos-virtualbox/blob/d00fde1543fb90fe63be4672fe2101f2ab82b2dc/macos-guest-virtualbox.sh#L476) because it thought Virtualbox was not starting up correctly, but it actually does.

See change here:
https://github.com/myspaghetti/macos-virtualbox/compare/master...loopy321:macos-virtualbox:patch-1

**Comment by myspaghetti** [comment]
I haven't been following VirtualBox NEM progress, and Oracle says it's still an [experimental feature](https://www.virtualbox.org/manual/UserManual.html#hyperv-support) so it might work with macOS now. I'll give it a look. At any rate this requires a lot of testing which I'm not about to do, so hopefully a [new maintainer](https://github.com/myspaghetti/macos-virtualbox/issues/645), if one ever shows up, will look into this more in-depth.

**Comment by myspaghetti** [comment]
Getting a macOS kernel panic on NEM/Hyper-V.
