### ISSUE TITLE
Where exactly do I have to type in "sudo diskutil repairDisk disk0"?

### ISSUE THREAD

**Issue by hyperpanthera** [img2tab/macos-guest-virtualbox#68]
I completed the installation, where do I type this in?

It says in the virtual machine but where?

**Comment by img2tab** [comment]
Terminal

**Comment by hyperpanthera** [comment]
@img2tab I did that but there is no partition named "Free Space" which I can erase.

**Comment by img2tab** [comment]
First resize the VDI in the VirtualBox media manager, then repair the partition table from the macOS guest Terminal, then delete the Free Space partition. If that doesn't work I'll have to get back to you later this week.

**Comment by hyperpanthera** [comment]
I skipped the resizing step in VirtualBox because it didn't tell me to do so. Perhaps you should include it in the script.

**Comment by hyperpanthera** [comment]
For me it says in the macOS guest:

Used: 25,64 GB
Other Volumes: 676,6 MB
Free: 40,58 GB

**Comment by hyperpanthera** [comment]
To what size do I resize the VDI in VirtualBox?

**Comment by img2tab** [comment]
Whatever size you want.
