### ISSUE TITLE
Anyone managed to connect an Apple device to the VM?

### ISSUE THREAD

**Issue by hyperpanthera** [img2tab/macos-guest-virtualbox#69]
I need it for Xcode!

**Comment by img2tab** [comment]
The USB support for iPhones and iPads is nit quite there yet on VirtualBox.

**Comment by hyperpanthera** [comment]
@img2tab You know what I did? I converted my .VDI to a VMware .VDMK and booted it in VMware. It is much faster on it and the USB works as well. I advise you to at least try it out and run it on VMware. No need to set anything extra or reinstall. Perhaps this script may shift to VMware.

**Comment by img2tab** [comment]
VMWare is closed-source commercial software, this script's goal is to use only open-source dependencies outside the host and guest OSes themselves.

**Comment by DuBistKomisch** [comment]
@hyperpanthera I've managed to convert and boot the image with vmware unlocker, but when I try to attach an ipad USB device the vm and/or ipad freeze/crash, any tips? I'm on arch linux host

**Comment by matteocrippa** [comment]
@DuBistKomisch do you have installed any powermanager? it can bring with you the lib to auto mount the iOS as filesystem and mess up

**Comment by Pflegusch** [comment]
Any news on this one? Have to use VirtualBox and cant seem to get my iPhone connected, even though Catalina recognizes the iPhone under a USB 2.0 Port.

**Comment by DuBistKomisch** [comment]
oh, I haven't tried this yet myself (I have an spare old macbook at the moment), but I read somewhere that passing through an entire USB controller to the guest works, rather than just the device
