### ISSUE TITLE
Could not download base

### ISSUE THREAD

**Issue by mikekenyon99** [img2tab/macos-guest-virtualbox#74]
I keep getting this error: "Could not download BaseSystem.dmg".  The problem is that it has already did in a previous step and is on disk fine. Also internet is working fine.. 

Mike

![Screenshot from 2019-06-28 18-55-15](https://user-images.githubusercontent.com/42475982/60361553-69e24b80-99d6-11e9-90fc-010514454d56.png)

**Comment by img2tab** [comment]
Whoops! Used the old filename! Fixed in version 0.65.2!

**Comment by img2tab** [comment]
Make that version 0.66.0...
